name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Build de l'image Docker
        run: docker build -t formation-app .

      - name: Simulation Test
        run: echo "L'image a été construite avec succès et est prête pour le déploiement."